added support for zapping replaceable events
nbd-wtf/nostr-tools pull request #424
Opened 2024-08-04 15:56 UTC by bitcoinpirate

fixes #291 

I tried to keep it backwards compatible by allowing the event id and the event object.

2024-08-04 15:59 UTC, fiatjaf commented
This code isn't zapping the replaceable event itself, but another replaceable events referenced by the target. To zap the replaceable event you would have to check if the target is replaceable, then build your own `a` tag from its `kind`, `pubkey` and `d` tag.

2024-10-21 15:03 UTC, AsaiToshiya requested changes

2024-10-21 15:03 UTC, AsaiToshiya commented on nip57.ts
> +    if ((10000 <= event.kind  && event.kind < 20000) || event.kind  == 0 || event.kind  == 3){
```suggestion
    if (10000 <= event.kind  && event.kind < 20000){
```

I don't think kind 0 and kind 3 events are addressable.

2024-10-21 15:03 UTC, AsaiToshiya commented on nip57.ts
> +      const a = ["a", `${event.kind}:${event.pubkey}`]
```suggestion
      const a = ["a", `${event.kind}:${event.pubkey}:`]
```

2025-01-22 01:42 UTC, SnowCait reviewed
@bitcoinpirate Nice PR, but is this still active?

2025-01-22 01:42 UTC, SnowCait commented on nip57.ts
> +    zr.tags.push(['e', event.id])
Forgot to delete?
```suggestion
```

2025-01-22 01:42 UTC, SnowCait commented on nip57.ts
> +    if ((10000 <= event.kind  && event.kind < 20000) || event.kind  == 0 || event.kind  == 3){
`isReplaceableKind` would be better.
https://github.com/nbd-wtf/nostr-tools/blob/1e5bfe856bfe953eb834e4bfa906cec5aed8cc88/kinds.ts#L9

2025-01-22 01:42 UTC, SnowCait commented on nip57.ts
> +    }else if (30000 <= event.kind && event.kind < 40000){
`isParameterizedReplaceableKind` would be better.
https://github.com/nbd-wtf/nostr-tools/blob/1e5bfe856bfe953eb834e4bfa906cec5aed8cc88/kinds.ts#L19

2025-01-22 01:42 UTC, SnowCait commented on nip57.ts
> +    }else if (30000 <= event.kind && event.kind < 40000){
White space.
```suggestion
    } else if (30000 <= event.kind && event.kind < 40000){
```

2025-01-22 02:27 UTC, AsaiToshiya commented
If there is no response from @bitcoinpirate, I will edit and merge theirs fork.

2025-02-21 16:36 UTC, AsaiToshiya commented
@SnowCait I applied your good suggestions.

2025-02-23 02:25 UTC, AsaiToshiya approved these changes

2025-02-23 02:37 UTC, AsaiToshiya commented
I will merge today.

2025-02-23 15:46 UTC, merged